### PR TITLE
Rewrite stonecutter recipe injection

### LINKED ISSUE #5: Incompatibility with Quilt Standard Libraries
QSL expects `getAvailableRecipes()` to return a correctly sized list here: https://github.com/QuiltMC/quilt-standard-libraries/blob/ef7cb80265918477a69990563b3251acf697bdf0/library/item/item_setting/src/main/java/org/quiltmc/qsl/item/setting/mixin/recipe_remainder/StonecutterOutputSlotMixin.java#L44-L45

The stacktrace:
```
java.lang.IndexOutOfBoundsException: Index 19 out of bounds for length 10
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2)
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.util.Objects.checkIndex(Objects.java:385)
	at java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.screen.StonecutterScreenHandler$2.redirect$ceh001$getRecipeRemainder(StonecutterScreenHandler:1047)
	at net.minecraft.screen.StonecutterScreenHandler$2.onTakeItem(StonecutterScreenHandler:74)
	at net.minecraft.screen.ScreenHandler.method_34249(ScreenHandler:423)
	at java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler:421)
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:293)
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager:450)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen:569)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen:361)
	at net.minecraft.client.gui.screen.ingame.StonecutterScreen.mouseClicked(StonecutterScreen:150)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
	at net.minecraft.client.util.Window.swapBuffers(Window:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1205)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:578)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
```

The full crash report: https://mclo.gs/pYUd7so

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #5

### CODE REVIEW

**Comment by Siuolplex** [comment]
Does this have any speed downsides for loading mods or similar? Have you tried the mod on Forge as well?

**Comment by magneticflux-** [comment]
I don't expect performance to change since it iterates over tagged items like it did before, and other mods shouldn't see the fake recipes because they aren't added to the `RecipeManager` to be searched for.

I've tested on Fabric (via the testmod) and Forge (with C+) and I don't see any change in behavior.

I'm testing some more with Quilt, which is why I marked it as a draft for now.

**Comment by magneticflux-** [comment]
So it turns out that Quilt's `StonecutterOutputSlotMixin#getRecipeRemainder` mixin ignores the `amount` parameter, assuming it to always be 1. This prevents our `StonecutterScreenHandlerOutputSlotMixin#stonecutterRecipeTags$redirectIntToShrinkInput` mixin from changing how many items are consumed. I'm reaching out to the Quilt developers that worked on https://github.com/QuiltMC/quilt-standard-libraries/pull/158 to see if that's something they can fix.

**Comment by magneticflux-** [comment]
I tested this PR with another PR fixing the issue in QSL and everything is working now: https://github.com/QuiltMC/quilt-standard-libraries/pull/219#issuecomment-1321066860

Forge and Fabric already worked before this PR (and still do), but now Quilt doesn't crash when trying to use fake recipes. Instead, QSL `3.0.0-beta.21+1.19.2` and below only takes 1 item from the input stack which can duplicate slabs, bricks, or anything else that requires multiple inputs to the stonecutter.

It's up to you all if you want to merge this now (and possibly add `"breaks": { "quilt_item_setting": "<=3.0.0-beta.21+1.19.2" }` to the `fabric.mod.json`) or wait until QSL releases the fix.

**Pull request merged**
